#ifndef XFOILLIB_GLOBAL_H
#define XFOILLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XFOILLIB_LIBRARY)
#  define XFOILLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XFOILLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XFOILLIB_GLOBAL_H
